name: Deploy AWS Lambda # Added 'name' field for better identification

on:
  push:
    branches:
      - main
    paths:
      - "lambda/"

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest # Sets or specifies the runner
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Python # Sets up our Python environment
        uses: actions/setup-python@v2 # Corrected 'setup-phython' to 'setup-python'
        with:
          python-version: "3.13" # Corrected 'phython-versions' to 'python-version'

      - name: Install Dependencies # Installs packages
        run: |
          python -m pip install --upgrade pip # Corrected 'phython' to 'python'
          pip install -r lambda/requirements.txt -t lambda # Corrected 'python install' to 'pip install'

      - name: Configure AWS Credentials # Sets up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} # Corrected syntax
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} # Corrected syntax
          aws-region: eu-west-1

      - name: Deploy our Lambda Function # Zips lambda directory and updates lambda function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd-lambda --zip-file fileb://lambda.zip # Corrected 'update-function-cde' to 'update-function-code'
